# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "âœ"
error_symbol = "âœ—"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 3

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 16
truncation_symbol = ""

[git_status]
conflicted = "ğŸš© "
ahead = "ğŸ ğŸ’¨ "
behind = "ğŸ˜° "
diverged = "ğŸ˜µ "
untracked = " ğŸ¤·â€"
stashed = "ğŸ“¦ "
modified = "âœï¸ "
staged = '[++\($count\)](green) '
renamed = "ğŸ‘… "
deleted = "ğŸ—‘ "

[memory_usage]
threshold = -1
symbol = "ğŸ "
style = "bold dimmed green"
disabled=false
format = "via $symbol [${ram_pct} / (${swap_pct})]($style) "

[nodejs]
symbol = "ğŸ¤– "

[rust]
symbol = "âš™ï¸ "
