# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = true
scan_timeout = "60"

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "symbol" segment is being set to "âœ"
error_symbol = "[âœ—](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
truncation_length = 16
truncation_symbol = ""

[git_status]
# conflicted = "ğŸ”´ "
# ahead = "ğŸğŸ’¨ "
# behind = "ğŸ˜° "
# diverged = "ğŸ˜µ "
# untracked = "ğŸ¤·â€ "
# stashed = "ğŸ“¦ "
# modified = "âœï¸ "
# staged = '[++$count](bold green)'
# renamed = "ğŸ‘… "
# deleted = "ğŸ—‘ "

[memory_usage]
threshold = -1
symbol = "ğŸ "
style = "bold dimmed green"
disabled = false

[nodejs]
symbol = "âœ¨ "

[rust]
symbol = "âš™ï¸ "